# Generated by Django 4.1.4 on 2023-02-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="file",
            new_name="url",
        ),
    ]
